<a href="https://colab.research.google.com/github/Joyal2127/Computer-vision/blob/main/normal_dist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.15.0


In [ ]:
torch.manual_seed(171)
torch.rand(3,3)

tensor([[0.3830, 0.0687, 0.4260],
        [0.0584, 0.7612, 0.7717],
        [0.8582, 0.2806, 0.1642]])

In [ ]:
torch.rand(4,4)

tensor([[0.1339, 0.8821, 0.6605, 0.9318],
        [0.6267, 0.4999, 0.5750, 0.8209],
        [0.9986, 0.2247, 0.6301, 0.7577],
        [0.6616, 0.0494, 0.8484, 0.8582]])

In [ ]:
torch.randint(-10, 10, (3,3))

tensor([[  5,   3, -10],
        [ -5,  -4,   3],
        [ -2,   2,   3]])